apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: final
  name: final
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      app: final
  template:
    metadata:
      labels:
        app: final
    spec:
      containers:
      - image: docker.io/luancv/final:latest
        name: final
        imagePullPolicy: Always
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "1024Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080