apiVersion: v1
kind: Service
metadata:
  name: capstone-project-service
spec:
  type: LoadBalancer
  selector:
    app: final-deployment
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
