apiVersion: v1
kind: Service
metadata:
  labels:
    service: server-app
  name: server-app
spec:
  type: LoadBalancer
  ports:
  - name: "8080"
    port: 8080
    targetPort: 8080
  selector:
    app: server-app