apiVersion: v1
kind: Service
metadata:
  labels:
    service: server-app
  name: server-app
spec:
  type: LoadBalancer
  ports:
  - name: "80"
    port: 80
    targetPort: 80
  selector:
    app: server-app