apiVersion: apps/v1
kind: Deployment
metadata:
  name: final-deployment
  labels:
    app: final-deployment
spec:
  replicas: 4
  selector:
    matchLabels:
      app: final-deployment
  template:
    metadata:
      labels:
        app: final-deployment
    spec:
      containers:
        - name: final-deployment
          image: luancv/final
          ports:
            - containerPort: 80
