---
- name: "Configure the EKS cluster with kubectl"
  hosts: management[0]
  user: ubuntu
  gather_facts: false
  become: yes
  vars:
    ENVIRONMENT_NAME: "{{ lookup('env', 'ENVIRONMENT_NAME') }}"
    DOCKERHUB_USERNAME: "{{ lookup('env','DOCKERHUB_USERNAME') }}"
    DOCKERHUB_PASSWORD: "{{ lookup('env','DOCKERHUB_PASSWORD') }}"
  roles:
    - final-deployment
    - final-service
