---
- name: "Authenticate AWS CLI with AWS"
  hosts: management
  user: ubuntu
  gather_facts: false
  become: yes
  vars:
    AWS_ACCESS_KEY_ID: "{{ lookup('env','AWS_ACCESS_KEY_ID') }}"
    AWS_SECRET_ACCESS_KEY: "{{ lookup('env','AWS_SECRET_ACCESS_KEY') }}"
    AWS_DEFAULT_REGION: "{{ lookup('env', 'AWS_DEFAULT_REGION') }}"
  tasks:
    - name: Set the aws_access_key_id
      shell: "aws configure set aws_access_key_id {{ AWS_ACCESS_KEY_ID }}"
    - name: Set the aws_secret_access_key
      shell: "aws configure set aws_secret_access_key {{ AWS_SECRET_ACCESS_KEY }}"
    - name: Set the default.region
      shell: "aws configure set default.region {{ AWS_DEFAULT_REGION }}"

- name: "LOGIN DOCKER"
  hosts: management
  user: ubuntu
  gather_facts: false
  become: yes
  vars:
    DOCKERHUB_USERNAME: "{{ lookup('env','DOCKERHUB_USERNAME') }}"
    DOCKERHUB_PASSWORD: "{{ lookup('env','DOCKERHUB_PASSWORD') }}"
  tasks:
    - name: LOGIN DOCKER
      shell: "docker login -u {{DOCKERHUB_USERNAME}} -p {{DOCKERHUB_PASSWORD}}"
- name: "Save LoadBalancer's DNS name locally"
  hosts: management[0]
  user: ubuntu
  gather_facts: false
  become: yes
  vars:
    ENVIRONMENT_NAME: "{{ lookup('env', 'ENVIRONMENT_NAME') }}"
  tasks:
    - name: Get the LoadBalancer's DNS name
      shell: "./bin/kubectl get svc {{ ENVIRONMENT_NAME }}"
      register: elb_dns
      args:
        chdir: $HOME

    - name: Copy the output to a local file
      copy:
        content: "{{ elb_dns.stdout }}"
        dest: "~/elb_dns.txt"
      delegate_to: localhost
