- name: Copy deployment configuration
  copy:
    src: "{{ ENVIRONMENT_NAME }}-deployment.yaml"
    dest: /home/ubuntu
- name: download
  shell: "curl -o aws-iam-authenticator curl -o aws-iam-authenticator https://amazon-eks.s3-us-west-2.amazonaws.com/1.13.7/2019-06-11/bin/linux/amd64/aws-iam-authenticator"
  args:
    chdir: /home//ubuntu
- name: Permission
  shell: "chmod +x ./aws-iam-authenticator"
  args:
    chdir: /home//ubuntu
- name: mv
  shell: "sudo mv ./aws-iam-authenticator /usr/local/bin/aws-iam-authenticator"
  args:
    chdir: /home//ubuntu
- name: aws_access_key_id
  shell: aws configure set aws_access_key_id {{AWS_ACCESS_KEY_ID}}

- name: AWS_SECRET_ACCESS_KEY
  shell: aws configure set aws_secret_access_key {{AWS_SECRET_ACCESS_KEY}}
         
- name: region
  shell: aws configure set region {{AWS_DEFAULT_REGION}}

- name: Run aws configure
  expect:
    command: aws configure
    responses:
      AWS Access Key ID: '{{AWS_ACCESS_KEY_ID}}'
      AWS Secret Access Key: '{{AWS_SECRET_ACCESS_KEY}}'
      Default region name: '{{AWS_DEFAULT_REGION}}'
      Default output format: ""
  no_log: true         
- name: update-kubeconfig
  shell: aws eks --region us-east-1 update-kubeconfig --name final-cluster
  args:
    chdir: $HOME
- name: Apply deployment configuration
  shell: "./kubectl apply -f {{ ENVIRONMENT_NAME }}-deployment.yaml"
  args:
    chdir: /home/ubuntu




